name: 一時的な権限付与

on:
  push:
    branches:
      - main
    paths:
      - 'request.csv'

jobs:
  add-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: GitHub CLIをセットアップ
        uses: cli/setup-gh@v1

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install pandas PyGithub python-dateutil

      - name: 権限を付与
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          python .github/scripts/add_permissions.py