name: 一時的な権限付与

on:
  issues:
    types: [labeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  approve-and-grant-permissions:
    runs-on: ubuntu-latest
    # 'Approved'ラベルが付けられた場合または手動実行の場合に実行
    if: github.event.label.name == 'Approved' || github.event_name == 'workflow_dispatch'
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          fetch-depth: 0

      - name: ラベル付与者の権限を確認
        id: check-permission
        if: github.event_name == 'issues'
        run: |
          # ラベルを付けたユーザー
          LABELER="${{ github.event.sender.login }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          
          # Issueの内容を取得
          ISSUE_BODY=$(gh issue view $ISSUE_NUMBER --json body | jq -r '.body')
          
          # Issue本文からチーム名を抽出
          TARGET_TEAM=$(echo "$ISSUE_BODY" | grep -o '付与したいチーム:.*' | sed 's/付与したいチーム://' | tr -d ' ' | tr -d '\r')
          echo "対象チーム: $TARGET_TEAM"
          
          # チーム名から承認者チームを決定
          if [[ "$TARGET_TEAM" == *"-write" ]]; then
            # -writeで終わる場合、対応する-dev-tlチームを承認者とする
            BASE_TEAM=${TARGET_TEAM%-write}
            APPROVER_TEAM="$BASE_TEAM-dev-tl"
          elif [[ "$TARGET_TEAM" == *"-dev-tl" ]]; then
            # -dev-tlの場合、同じチームを承認者とする
            APPROVER_TEAM="$TARGET_TEAM"
          else
            # その他の場合もチームをそのまま使用
            APPROVER_TEAM="$TARGET_TEAM"
          fi
          
          echo "承認者チーム: $APPROVER_TEAM"
          ORG_NAME="Daihatsu-Connect"
          
          # ユーザーが承認者チームに所属しているか確認
          HAS_PERMISSION=false
          
          # チームの直接メンバー一覧を取得して表示
          echo "チーム $ORG_NAME/$APPROVER_TEAM の直接メンバー一覧:"
          TEAM_MEMBERS=$(gh api "orgs/$ORG_NAME/teams/$APPROVER_TEAM/members" --jq '.[].login' 2>/dev/null || echo "チームが見つからないか、メンバー一覧を取得できません")
          echo "$TEAM_MEMBERS"
          
          # ラベル付与者が直接メンバーのリストに含まれているか確認
          if echo "$TEAM_MEMBERS" | grep -q "^$LABELER$"; then
            HAS_PERMISSION=true
            echo "ユーザー $LABELER は $ORG_NAME/$APPROVER_TEAM の直接メンバーです"
          else
            echo "ユーザー $LABELER は $ORG_NAME/$APPROVER_TEAM の直接メンバーではありません"
          fi
          
          # 承認者チームが存在しない場合や承認権限がない場合はCODEOWNERSにフォールバック
          if [ "$HAS_PERMISSION" != "true" ] && [ -f ".github/CODEOWNERS" ]; then
            echo "承認者チームのメンバーではありません。CODEOWNERSを確認します。"
            # CODEOWNERSファイルからチーム名を抽出（@org/team-name の形式）
            TEAMS=$(grep -o '@[^ ]*' .github/CODEOWNERS | sort | uniq | tr '\n' ' ')
            echo "CODEOWNERSから抽出したチーム: $TEAMS"
            
            # ユーザーがいずれかのチームに所属しているか確認
            for TEAM in $TEAMS; do
              # チーム名から組織名とチームスラグを抽出
              if [[ $TEAM =~ @([^/]+)/(.+) ]]; then
                CODEOWNER_ORG="${BASH_REMATCH[1]}"
                CODEOWNER_TEAM="${BASH_REMATCH[2]}"
                
                echo "チームを確認中: $CODEOWNER_ORG/$CODEOWNER_TEAM"
                
                # チームの直接メンバー一覧を取得して表示
                echo "チーム $CODEOWNER_ORG/$CODEOWNER_TEAM の直接メンバー一覧:"
                CODEOWNER_MEMBERS=$(gh api "orgs/$CODEOWNER_ORG/teams/$CODEOWNER_TEAM/members" --jq '.[].login' 2>/dev/null || echo "チームが見つからないか、メンバー一覧を取得できません")
                echo "$CODEOWNER_MEMBERS"
                
                # ラベル付与者が直接メンバーのリストに含まれているか確認
                if echo "$CODEOWNER_MEMBERS" | grep -w "$LABELER" > /dev/null; then
                  HAS_PERMISSION=true
                  echo "ユーザー $LABELER は $CODEOWNER_ORG/$CODEOWNER_TEAM の直接メンバーです"
                  break
                else
                  echo "ユーザー $LABELER は $CODEOWNER_ORG/$CODEOWNER_TEAM の直接メンバーではありません"
                fi
              fi
            done
          fi
          
          if [ "$HAS_PERMISSION" = "true" ]; then
            echo "has_permission=true" >> $GITHUB_OUTPUT
            echo "承認権限を持つユーザーです: $LABELER"
          else
            echo "has_permission=false" >> $GITHUB_OUTPUT
            echo "承認権限を持たないユーザーです: $LABELER"
            
            # ラベルを削除
            gh api --method DELETE "/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels/Approved"
            
            # エラーメッセージをコメント
            gh issue comment "$ISSUE_NUMBER" --body "⚠️ 承認権限がありません。このラベルは承認権限を持つユーザーのみが付与できます。"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          
      - name: 関連PRを検索
        id: find-pr
        if: github.event_name == 'issues' && (steps.check-permission.outputs.has_permission == 'true' || steps.check-permission.outcome == 'skipped')
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          
          # Issueの内容を取得して対象チームを抽出（元のチームを保持するため）
          ISSUE_BODY=$(gh issue view $ISSUE_NUMBER --json body | jq -r '.body')
          TARGET_TEAM=$(echo "$ISSUE_BODY" | grep -o '付与したいチーム:.*' | sed 's/付与したいチーム://' | tr -d ' ' | tr -d '\r')
          echo "対象チーム（追加先）: $TARGET_TEAM"
          
          # request.csvを更新して元の対象チームを使用
          if [ -f "request.csv" ]; then
            # 現在のrequest.csvの内容を取得
            CURRENT_REQUEST=$(cat request.csv)
            # 最初のカンマまでの部分を対象チームに置き換え
            NEW_REQUEST=$(echo "$CURRENT_REQUEST" | sed "s/^[^,]*/$TARGET_TEAM/")
            # 更新したrequest.csvを書き込み
            echo "$NEW_REQUEST" > request.csv
            echo "request.csvを更新しました: $NEW_REQUEST"
          else
            echo "警告: request.csvが見つかりません"
          fi
          
          # PRの本文に「Issue #XX」という形式で関連Issueが記載されているPRを検索
          PR_INFO=$(gh pr list --search "Issue #$ISSUE_NUMBER in:body" --json number,url,title --jq '.[0]')
          
          if [ -n "$PR_INFO" ]; then
            PR_NUMBER=$(echo "$PR_INFO" | jq -r '.number')
            PR_URL=$(echo "$PR_INFO" | jq -r '.url')
            
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
            echo "関連PRを発見: #$PR_NUMBER ($PR_URL)"
          else
            echo "関連PRが見つかりません"
            gh issue comment "$ISSUE_NUMBER" --body "❌ このIssueに関連するPRが見つかりませんでした。本IssueをCloseして再度Issueを作成してください。"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          
      - name: PRをマージ
        if: github.event_name == 'issues' && steps.find-pr.outputs.pr_number != ''
        run: |
          PR_NUMBER="${{ steps.find-pr.outputs.pr_number }}"
          
          # PRをマージ（管理者権限を使用）
          gh pr merge $PR_NUMBER --merge --delete-branch --admin
          
          # マージ後にmainブランチをチェックアウト
          git fetch origin main
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install pandas PyGithub python-dateutil

      - name: 権限を付与
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        id: add-permissions
        run: |
          python .github/scripts/add_permissions.py | tee output_log.txt
          
      - name: 結果を保存
        run: |
          grep "^成功\|^エラー" output_log.txt > output_summary.txt || true
          
      - name: 結果をアーティファクトとして保存
        uses: actions/upload-artifact@v4
        with:
          name: execution-results
          path: |
            output_log.txt
            output_summary.txt
          retention-days: 90
          
      - name: 台帳をリポジトリにコミット
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # request.csvの変更をリセット
          git checkout -- request.csv || true
          
          # mainブランチの最新の変更を取得
          git fetch origin main
          git checkout main
          git pull origin main  # 最新の変更を取得
          
          # 台帳ファイルを更新
          cp permissions_ledger.csv permissions_ledger.csv.new
          git checkout main -- permissions_ledger.csv || true
          
          # ヘッダー行を作成
          echo "team_name,username,end_date,status" > permissions_ledger.csv.header
          
          if [ -f permissions_ledger.csv ]; then
            # 既存の台帳からヘッダーを除外してデータ行のみを取得
            grep -v "^team_name,username,end_date,status" permissions_ledger.csv > permissions_ledger.csv.data || true
            # 新しい台帳からヘッダーを除外してデータ行のみを取得
            grep -v "^team_name,username,end_date,status" permissions_ledger.csv.new > permissions_ledger.csv.new.data || true
            
            # データ行をマージしてソート
            cat permissions_ledger.csv.data permissions_ledger.csv.new.data | sort | uniq > permissions_ledger.csv.merged
            
            # ヘッダー行とデータ行を結合
            cat permissions_ledger.csv.header permissions_ledger.csv.merged > permissions_ledger.csv
          else
            # 既存の台帳がない場合は、ヘッダー行と新しい台帳のデータ行を結合
            grep -v "^team_name,username,end_date,status" permissions_ledger.csv.new > permissions_ledger.csv.new.data || true
            cat permissions_ledger.csv.header permissions_ledger.csv.new.data > permissions_ledger.csv
          fi
          
          # 一時ファイルを削除
          rm -f permissions_ledger.csv.header permissions_ledger.csv.data permissions_ledger.csv.new.data permissions_ledger.csv.merged permissions_ledger.csv.new
          
          # 変更をコミット
          git add permissions_ledger.csv
          git commit -m "台帳を更新 [skip ci]" || echo "変更なし"
          git push origin main
          
      - name: Issueに通知
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          
          # 申請者のユーザー名を取得
          ISSUE_INFO=$(gh issue view $ISSUE_NUMBER --json author)
          REQUESTER=$(echo "$ISSUE_INFO" | jq -r '.author.login')
          REQUESTER_MENTION="@$REQUESTER"
          
          # 結果の要約を取得
          if [ -f "output_summary.txt" ]; then
            RESULT=$(cat output_summary.txt)
          else
            RESULT="結果の詳細が見つかりません"
          fi
          
          # Issueにコメント
          SUCCESS_MSG="$REQUESTER_MENTION
          
          ## 権限付与が完了しました ✅
          
          ### 処理結果:
          \`\`\`
          $RESULT
          \`\`\`
          
          権限が正常に付与されました。"
          
          gh issue comment "$ISSUE_NUMBER" --body "$SUCCESS_MSG"
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}