name: 一時的な権限付与

on:
  push:
    branches:
      - main
    paths:
      - 'request.csv'
  workflow_dispatch:

jobs:
  add-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install pandas PyGithub python-dateutil

      - name: 権限を付与
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        id: add-permissions
        run: |
          python .github/scripts/add_permissions.py | tee output_log.txt
          
      - name: 結果を保存
        run: |
          grep "^成功\|^エラー" output_log.txt > output_summary.txt || true
          
      - name: 結果をアーティファクトとして保存
        uses: actions/upload-artifact@v3
        with:
          name: execution-results
          path: |
            output_log.txt
            output_summary.txt
          retention-days: 90