name: 一時的な権限付与

on:
  push:
    branches:
      - main
    paths:
      - 'request.csv'
  workflow_dispatch:

jobs:
  add-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install pandas PyGithub python-dateutil

      - name: 権限を付与
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        id: add-permissions
        run: |
          python .github/scripts/add_permissions.py | tee output_log.txt
          
      - name: 結果を保存
        run: |
          grep "^成功\|^エラー" output_log.txt > output_summary.txt || true
          
      - name: 結果をリポジトリに保存
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          cp output_log.txt execution_log.txt
          cp output_summary.txt execution_summary.txt
          git add execution_log.txt execution_summary.txt
          git commit -m "権限付与の実行結果を更新 [skip ci]" || echo "変更なし"
          git push