name: Issueからの権限申請

on:
  issues:
    types: [opened]

# GitHub Actionsのトークンに必要な権限を付与
permissions:
  contents: write    # リポジトリの内容を変更する権限
  pull-requests: write  # PRを作成する権限
  issues: write      # Issueにコメントする権限
  id-token: write       # IDトークンを使用する権限

jobs:
  create-request:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: ブランチ名を生成
        id: generate-branch
        run: |
          LAST_NUM=$(git branch -r | grep 'origin/request/' | sed 's/.*request\///' | sort -n | tail -n 1 || echo "0")
          NEXT_NUM=$((LAST_NUM + 1))
          BRANCH_NAME="request/$NEXT_NUM"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "新しいブランチ名: $BRANCH_NAME"

      - name: Issue本文を解析してCSVに変換
        run: |
          echo "${{ github.event.issue.body }}" | python .github/scripts/parse_issue.py > request.csv
          cat request.csv
      
      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub python-dateutil

      - name: 申請内容を検証
        id: validate-request
        run: |
          python .github/scripts/validate_request.py
          if [ $? -ne 0 ]; then
            ERROR_MSG="❌ 申請内容の検証に失敗しました。本issueをcloseし、issueを新規作成してください。"
            gh issue comment "${{ github.event.issue.number }}" --body "$ERROR_MSG"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}  # 検証には管理者権限が必要
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}  # コメントにも管理者権限を使用

      - name: ブランチを作成
        id: create-branch
        run: |
          BRANCH_NAME="${{ steps.generate-branch.outputs.branch_name }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          
          # GitHub Actionsボットとして設定
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          git checkout -b "$BRANCH_NAME"
          
          # 変更を強制的に追加
          git add -f request.csv
          
          # 空のコミットも許可してコミット
          git commit -m "権限申請を追加 (Issue #$ISSUE_NUMBER)" --allow-empty || true
          
          # プッシュ
          git push origin "$BRANCH_NAME"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        
      - name: PRを作成
        id: create-pr
        if: steps.create-branch.outputs.has_changes == 'true'
        run: |
          PR_URL=$(gh pr create --base main --head "${{ steps.generate-branch.outputs.branch_name }}" --title "権限申請 (Issue #${{ github.event.issue.number }})" --body "Issue #${{ github.event.issue.number }} からの権限申請")
          echo "pr_url=${PR_URL}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          
      - name: 承認者情報を取得
        id: get-approvers
        if: steps.create-branch.outputs.has_changes == 'true'
        run: |
          # CODEOWNERSファイルからチームを抽出
          APPROVERS=""
          if [ -f ".github/CODEOWNERS" ]; then
            # CODEOWNERSファイルからチーム名を抽出（@org/team-name の形式）
            TEAMS=$(grep -o '@[^ ]*' .github/CODEOWNERS | sort | uniq | tr '\n' ' ')
            APPROVERS="$TEAMS"
          else
            # デフォルトの承認者リスト
            APPROVERS="@dmc-nyoshida"
          fi
          echo "approvers=$APPROVERS" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}

      - name: Issueにコメント
        if: steps.create-branch.outputs.has_changes == 'true'
        run: |
          # 申請者のユーザー名を取得
          REQUESTER="${{ github.event.issue.user.login }}"
          
          # 承認者へのメンション
          APPROVERS="${{ steps.get-approvers.outputs.approvers }}"
          
          SUCCESS_MSG="${APPROVERS}
          
          ## 権限申請を実行します。✅
          承認されるまでお待ちください。
          
          承認者は、このIssueに「Approved」ラベルを付けてください。"
          
          gh issue comment "${{ github.event.issue.number }}" --body "$SUCCESS_MSG"
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          
      - name: エラー時の処理
        if: failure()
        run: |
          ERROR_MSG="❌ 権限申請の処理中にエラーが発生しました。本issueをcloseし、issueを新規作成してください。：
          次の間違いを確認。
          - 「# 以下を編集」から「---」までの間に必要な情報が記載されているか
          - 「付与したいチーム:」「付与するユーザ:」「期限:」の項目が記載されているか
          - チーム名とユーザー名が正しいか
          - 期限が正しい形式（YYYYMMDD）で記載されているか"
          
          gh issue comment "${{ github.event.issue.number }}" --body "$ERROR_MSG"
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}