name: Issueからの権限申請

on:
  issues:
    types: [opened]

jobs:
  create-request:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          fetch-depth: 0  # すべての履歴を取得

      - name: ブランチ名を生成
        id: generate-branch
        run: |
          # 既存のブランチから最大の番号を取得
          LAST_NUM=$(git branch -r | grep 'origin/request/' | sed 's/.*request\///' | sort -n | tail -n 1 || echo "0")
          # 次の番号を計算
          NEXT_NUM=$((LAST_NUM + 1))
          # ブランチ名を生成
          BRANCH_NAME="request/$NEXT_NUM"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "新しいブランチ名: $BRANCH_NAME"

      - name: ブランチを作成
        id: create-branch
        run: |
          BRANCH_NAME="${{ steps.generate-branch.outputs.branch_name }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b "$BRANCH_NAME"
          
          # Issue本文をrequest.csvに保存
          echo "${{ github.event.issue.body }}" > request.csv
          
          # ファイルを追加してコミット
          git add request.csv
          if git commit -m "権限申請を追加 (Issue #$ISSUE_NUMBER)"; then
            echo "コミットが成功しました"
            git push origin "$BRANCH_NAME"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "エラー: コミットに失敗しました。変更がないか、他の問題があります。"
            echo "has_changes=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        
      - name: PRを作成
        id: create-pr
        if: steps.create-branch.outputs.has_changes == 'true'
        run: |
          PR_URL=$(gh pr create --base main --head "${{ steps.generate-branch.outputs.branch_name }}" --title "権限申請 (Issue #${{ github.event.issue.number }})" --body "Issue #${{ github.event.issue.number }} からの権限申請")
          echo "pr_url=${PR_URL}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          
      - name: Issueにコメント
        if: steps.create-branch.outputs.has_changes == 'true'
        run: |
          COMMENT="## PRを作成しました ✅

承認されるまでお待ちください。

PR: ${{ steps.create-pr.outputs.pr_url }}"
          gh issue comment "${{ github.event.issue.number }}" --body "$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          
      - name: エラー時の処理
        if: failure()
        run: |
          COMMENT="❌ 権限申請の処理中にエラーが発生しました。

以下を確認してください：
1. Issue本文が正しいCSV形式で記載されているか
2. チーム名とユーザー名が正しいか
3. 終了日が正しい形式（YYYYMMDD）で記載されているか"
          gh issue comment "${{ github.event.issue.number }}" --body "$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}